base:
  is_2D: 1
  is_3D: 0
  is_R50: 1
  is_SAMVIT: 0
  dataset_name: buidnewprocess
  gpu_id: '5'
  original_checkpoint: 'vissl-1M-graph-match' #'vissl-1M-graph-match' # Original checkpoint from segment-anything project
  best_valid_model_checkpoint: './working_dir/checkpoint/BUID_R50'
  image_shape: 256

train:
  train_batch_size: 8
  valid_batch_size: 1
  test_batch_size: 1
  optimizer: 'adam'
  learning_rate: 0.0001
  num_epochs: 50
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0
  scheduler: 0

dataloader:
  train_dir_img: '/home/caduser/Foundmed_Experiment/Segmentation/BUID_new_process/train' #'./dataset_demo/BUID/train'
  train_dir_mask: '/home/caduser/Foundmed_Experiment/Segmentation/BUID_new_process/train_labels' #'./dataset_demo/BUID/train_labels'
  valid_dir_img: '/home/caduser/Foundmed_Experiment/Segmentation/BUID_new_process/valid' #'./dataset_demo/BUID/valid'
  valid_dir_mask: '/home/caduser/Foundmed_Experiment/Segmentation/BUID_new_process/valid_labels' #'./dataset_demo/BUID/valid_labels'
  test_dir_img: '/home/caduser/Foundmed_Experiment/Segmentation/BUID_new_process/test' #'./dataset_demo/BUID/test'
  test_dir_mask: '/home/caduser/Foundmed_Experiment/Segmentation/BUID_new_process/test_labels' #'./dataset_demo/BUID/test_labels'
  have_label: '/home/caduser/Foundmed_Experiment/Segmentation/BUID_new_process/have_label.txt' #'./dataset_demo/BUID/have_label.txt'
  non_label: '/home/caduser/Foundmed_Experiment/Segmentation/BUID_new_process/non_label.txt' #'./dataset_demo/BUID/non_label.txt'